version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      php: 7.3
  pre_build:
    commands:
      - echo Installing composer dependencies
      - composer install
      - echo Logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building Docker image on `date`
      - docker build --build-arg dbu=${DATABASE_USERNAME} --build-arg dbp=${DATABASE_PASSWORD} --build-arg dbh=${DATABASE_HOST} --build-arg dbn=wordpress -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"wordpress","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

