version: '3'

services:
  
  wordpress:
    build:
      context: .
      args:
        dbu: root
        dbp: password
        dbh: mysql
        dbn: wordpress
    image: wordpress/vedagraceclinic.com:local
    restart: always
    ports:
      - "8080:80"
    depends_on: 
      - mysql
    volumes:
      - ./site/wp-content:/var/www/html/wp-content

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./local/mysql:/var/lib/mysql
    ports: 
      - "3306:3306"